### ISSUE TITLE
YCD export->import inconsistencies

### ISSUE THREAD

**Issue by grzybeek** [Skylumz/Sollumz#335]
I've been messing around with animations for few days (also i'm new blender user, so maybe i'm doing something wrong?) and I encountered few issues, I've recorded everything on a video, so maybe it will be better than my writing skills 😄

**Video link:** https://streamable.com/jp624u

**1)** With each export -> import, "end frame" and "duration" increases by one
Example on a video above:
Import: gdance1 end frame = 246, duration 10.21
After export->import again: gdance1 end frame = 247, duration 10.25
Import: gdance2 end frame = 215, duration 8.92
After export->import again: gdance2 end frame = 216 duration 8.96

**2)** Root rotation/location swaps between clips (at first gdance1 clip was "moving around", after export->import, gdance2 was "moving around" and gdance1 was in place). At first both clips were made that they don't move at all, it started happening after first import *I think*

**3)** There is some error after hitting "Apply Clip to NLA" button (visible at the end of the video)

If needed I can send .ycd.xml in Discord DM's (grzybeek#9100) or somewhere private (I wouldn't want to upload it publicly)

**Comment by ultrahacx** [comment]
I don't think you are using the latest Sollumz version. Make sure you are using Blender 3.0 or 3.1 for best compatibility and are on latest Sollumz branch.

1- Duration is calculated automatically for certain cases using your Blender output frame rate value. By default the value is set at 24FPS in Blender and hence: 246/24 = 10.25 seconds. 

2- This might be due to incorrect workflow or simply a bad animation. As shown in the video, you never resetted the armature position after you exported and deleted the YCD. It is always recommended that you use a fresh armature or atleast reset the armature properties so that its at origin and at default rest pose.

3- As said, this is probably because you are not using the latest Sollumz version. That error was fixed a while ago.

**Comment by grzybeek** [comment]
Actually Blender should be latest(I'm using steam version so it should update automatically?), before recording video I've downloaded latest Sollumz (4 hours after last commit) - Last one was removed from addons, and new one installed, I think this is proper way to change versions?

I understand duration changes because it is calculated from frames count, but why does end frame increases by one? After few export->import I'll have few empty frames at the end.

Both animations were created on a "fresh" ped model, as you can see on video I'm opening "template.blend" after exporting ycd, it is just bare ped. So armature should be resetted, animations were taken from Mixamo and as I told before, at first both were exported without root moving


Unfortunately I'll be home in ~3 days, so can't test/check anything right now.

**Comment by grzybeek** [comment]
Okay, so I'm back home and I've checked everything once again.
Blender is not from steam, but it is version 3.1.0, Sollumz has been updated to latest one again ("Apply Clip to NLA" error is gone, so probably I've did something wrong last time updating it)

But the issue is still here, I've recorded second video with just one animation, exported and imported it few times https://streamable.com/njgdq4

With each export->import end frame amount was increasing by one and root position/rotation was changing.
[animxml.zip](https://github.com/Skylumz/Sollumz/files/8766944/animxml.zip)
Here is .ycd.xml used on video above, so anyone can check it by himself :)

**Comment by Trucker7** [comment]
Good afternoon, I'm just a normal user, I'm in this section because the plugin has helped me infinitely in many things and I appreciate it a lot. I have a problem, and it is that yes, in terms of animations I can import them and everything is fine, no problem, except in some exclusive ones, it is the facial animation that is responsible for animating the character's face. The problem is that when I import it into the program to be able to animate the face, the animation appears to appear, but when I give it apply clip to NLA, it doesn't animate the skeleton of the character, it stays the same, until I go to where the action editor is and nonlinear animation and nothing. The animation for all the parts of the body that does not include a face animates them for me, but the specific animation for the face does not, and the names of the different parts of the bones are fine, because if they were not, obviously everything else would not animate. I would like to know if there is any solution to this detail. I would really appreciate this little help.
